# Generated by Django 6.1.1 on 2026-09-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('general', 'Consulta podológica general'), ('quiropodia', 'Quiropodia (atención de callos y durezas)'), ('uña_encarnada', 'Tratamiento de uña encarnada'), ('hongos', 'Tratamiento de hongos (onicomicosis)'), ('pie_diabetico', 'Atención de pie diabético'), ('verrugas', 'Tratamiento de verrugas plantares')], default='general', max_length=30)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('appointment_date', 'appointment_time'), name='unique_appointment_slot')],
            },
        ),
    ]
