# Generated by Django 6.1.1 on 2026-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(default='general', max_length=150),
        ),
    ]
