"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables del archivo .env en desarrollo local. En Render no existe
# .env y las variables vienen del panel (las ya definidas no se sobrescriben).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False: solo se activa con DEBUG=True en el .env local.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('Falta la variable de entorno SECRET_KEY.')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'podogest-frontend.vercel.app', '.onrender.com', 'www.pasossaludables.cl' ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',  # Django REST Framework: serializers y vistas de la API
    'corsheaders',     # Permite peticiones cross-origin desde el frontend
    # Local
    'api',             # App de citas de podogest
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Debe ir lo más arriba posible, antes de WhiteNoise y CommonMiddleware,
    # para poder añadir las cabeceras CORS a todas las respuestas.
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Usa DATABASE_URL (PostgreSQL en Render); sin ella, SQLite local.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Cache
# Guardada en la base de datos para que los contadores de rate limiting se
# compartan entre todos los workers de Gunicorn. La tabla se crea con:
#   python manage.py createcachetable
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'podogest_cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Carpeta donde `collectstatic` reúne los archivos que WhiteNoise sirve en producción.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_STORAGE ya no existe desde Django 5.1: se configura con STORAGES.
# WhiteNoise comprime los archivos y les añade un hash para cachearlos sin riesgo.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# CORS
# Solo los orígenes listados pueden llamar a esta API desde el navegador.
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite (desarrollo local)
    'http://127.0.0.1:5173',
]

# URLs del frontend en producción, separadas por comas. Ej. en Render:
#   FRONTEND_URLS=https://podogest-frontend.vercel.app
# Deben incluir el esquema (https://) y no terminar en '/'.
CORS_ALLOWED_ORIGINS += [
    url.strip().rstrip('/')
    for url in os.environ.get('FRONTEND_URLS', 'https://podogest-frontend.vercel.app,https://pasossaludables.cl,https://www.pasossaludables.cl').split(',')
    if url.strip()
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Configuración de envío de correos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Django REST Framework
# Autenticación con tokens JWT (simplejwt) para el panel de administración.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Rate limiting: límite general para cualquier petición anónima
    # (incluye /api/token/, lo que frena ataques de fuerza bruta al login).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        # Límites estrictos solo para crear reservas (ver api/throttles.py).
        'reservas_burst': '5/min',
        'reservas_sustained': '20/hour',
    },
    # Número de proxies delante de Django: 1 por defecto (Render). Ajustable con
    # la variable NUM_PROXIES. Sin esto, DRF confía en X-Forwarded-For completo
    # y un atacante podría falsearlo para saltarse el límite.
    'NUM_PROXIES': int(os.environ.get('NUM_PROXIES', '1')),
}
